---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: infra
name: convert2rhel
version: "1.0.0"
readme: README.md
authors:
  - Rodolfo Olivieri (github.com/r0x0d)
description: Ansible collection for running the convert2rhel tool
license_file: LICENSE
tags:
  # tags so people can search for collections https://galaxy.ansible.com/search
  # tags are all lower-case, no spaces, no dashes.
  - rhel
  - conversions
  - linux
repository: https://github.com/redhat-cop/infra.convert2rhel
documentation: https://github.com/redhat-cop/infra.convert2rhel/tree/main/docs
homepage: https://github.com/redhat-cop/infra.convert2rhel
issues: https://github.com/redhat-cop/infra.convert2rhel/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - extensions
dependencies:
  ansible.posix: ">=1.5.1"
  community.general: ">=6.6.0"
  ansible.utils: ">=2.12.0"
...
